### ISSUE TITLE
migrate openstack and rackspace projects to a new repo jclouds-labs-openstack

### ISSUE THREAD

**Issue by codefromthecrypt** [jclouds/legacy-jclouds-labs#35]
Since the openstack, rackspace, and hp code share the same dependencies, let's migrate openstack and rackspace (and future hp) lab projects to a new repo jclouds-labs-openstack so that they can be revved, reviewed, and released independently.

cc @jdaggett @everett-toews

**Comment by andrewgaul** [comment]
Done.
